name: format

on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: akaihola/darker@1.4.0
        with:
          options: "--check --verbose"
          src: "./nextcord"
          # TODO: Remove "version" on the next darker release.
          # By default, this should use the same version of darker as written above,
          # but v1.4.0 of the github action had a bug where darker 1.3.2 was still
          # being used. See https://github.com/akaihola/darker/pull/282 for details.
          version: "1.4.0"
